### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by mariocorradetti** [liuziyang123/FAMINet#1]
The link of the download leads to an empty page where there are no downloadable models. Is possible to have new link?
Thank you in advance

**Comment by liuziyang123** [comment]
Hi, sorry for the late reply. We have updated the link and now you can download the models from [here](https://drive.google.com/drive/folders/1WhIYaXHx8zhZQ4Nat1_HbM8mQd8z5UZS?usp=sharing).
