### ISSUE TITLE
The part that calculates the optical flow was removed and this code is not complete

### ISSUE THREAD

**Issue by lifenghong** [liuziyang123/FAMINet#3]
The part that calculates the optical flow was removed and this code is not complete

**Comment by liuziyang123** [comment]
Hi, thanks for your attention. We will fix the bug and re-run the codes ASAP.

**Comment by liuziyang123** [comment]
Hi, the codes are fixed.

For training, the FAMINet is trained with optical flow provided by the RAFT, in [line](https://github.com/liuziyang123/FAMINet/blob/main/model/seg_network.py#L227).

Note that the parameters of RAFT should be fixed during training.

For test, the FAMINet is running with optical flow optimized by the proposed RSD algorithm in [line](https://github.com/liuziyang123/FAMINet/blob/main/model/tracker.py#L421).
